export { home } from "./home";
export { events } from "./events";
export { innovationDay } from "./innovation-day";
export { inTalks } from "./in-talks";
export { internalEvent } from "./internal-event";
export { relatedEvents } from "./detail";
export { faqs } from "./faq";
export { response } from "./response";
export { speaker } from "./speaker";
